config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

  resources :users, only: [:show, :edit, :update, :index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  # has_many :profile_image_id_to_users, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
    user_path(current_user.id)
    end

    def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
    end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
        before_action :authenticate_user!
    before_action :correct_user, only: [:edit, :update, :destroy]

    def index
        @books = Book.all
        @book = Book.new
        @user = current_user
    end

    def show
        @books = Book.find(params[:id])
        @book = Book.new
        @user = @books.user
    end

	def new
		@book = Book.new
    end

    def create
    	@book = Book.new(book_params)
    	@book.user_id = current_user.id
    	if @book.save
           flash[:notice] = "You have creatad book successfully."
    	   redirect_to book_path(@book)
        else
            @books = Book.all
            @user = current_user
            render :index
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
           flash[:notice] = "You have updated book successfully."
           redirect_to book_path(@book.id)
       else
           render :edit
       end
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path
    end



    private
    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end

    def correct_user
      @book = Book.find(params[:id])
      redirect_to books_path if current_user != @book.user
    end

end

# @books = Book.all.page(params[:page]).reverse_order

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end

	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) if current_user != @user
  end


end


# @post_image = PostImage.find(params[:id])

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="body">
  <div class="container">

   <% if @book.errors.any? %>
    <div id="error_explanation">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>


    <div class="row">
	    <div class="col-md-6 col-md-offset-3">
		    <h1>Editing Book</h1>
  <!-- <div class='col-md-3 col-md-offset-3'>
  </div> -->
      </div>
      <div class="edit_book">
  		  <%= form_for(@book) do |f| %>
         <div class="field row">
           <label for="book_title">Title</label>
           <%= f.text_field :title, class:"col-xs-12 book_title" %>
          </div>

         <div class="field row">
           <label for="book_opinion">Opinion</label>
           <%= f.text_area :body, class:"col-xs-12 book_body" %>
         </div>

         <div class="actions row">
          <%= f.submit "Update Book", class:"btn btn-primary col-xs-12" %>
         </div>
        <% end %>
      </div>

      <%= link_to "Show", book_path(@book.id) %>
  		<%= link_to "Back", books_path %>

      </div>
      <div class="col-md-3"></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<!-- サクセスメッセージ -->
<%= render 'template/flash.message' %>

<div class="row" style="user-select: auto;">
<!-- エラーメッセージ -->
<% if @book.errors.any? %>
    <div id="error_explanation">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>



  <!-- 左側 -->
<%= render 'template/sidebar' %>


  <!-- 右側 -->

  <div class="col-xs-9" style="user-select: auto;">
    <h2 style="user-select: auto;">Books</h2>

    <table class="table table-hover table-inverse" style="user-select: auto;">
  <thead style="user-select: auto;">
    <tr style="user-select: auto;">
      <th style="user-select: auto;"></th>
      <th style="user-select: auto;">Title</th>
      <th style="user-select: auto;">Opinion</th>
      <th colspan="3" style="user-select: auto;"></th>
    </tr>
  </thead>

  <tbody style="user-select: auto;">
    <% @books.each do |book| %>

      <tr style="user-select: auto;">
        <td style="user-select: auto;">
          <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td style="user-select: auto;"><%= link_to "#{book.title}", book_path(book.id) %></td>
        <td style="user-select: auto;"><%= book.body %></td>
      </tr>

    <% end %>

  </tbody>
</table>
  </div>








</div>

app/views/books/show.html.erb
<!-- サクセスメッセージ -->
<%= render 'template/flash.message' %>

<div class="row" style="user-select: auto;">

<!-- 左側 -->
<%= render 'template/sidebar' %>

<!-- 右側 -->

  <div class="col-xs-9" style="user-select: auto;">
		<h2 style="user-select: auto;">Book detail</h2>
		<table class="table" style="user-select: auto;">
		  <tbody style="user-select: auto;">
        <tr style="user-select: auto;">
          <td style="user-select: auto;">
            <%= link_to user_path(@books.user_id) do %>
            <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>

            <% end %> <!-- 変更 -->
            <%= link_to @books.user.name, user_path(@books.user_id) %>
          </td>
          <td style="user-select: auto;"><%= link_to "#{@books.title}", book_path(@books.id) %></td> <!-- 変更 -->
          <td style="user-select: auto;"><%= @books.body %></td> <!-- 変更 -->
          <% if @books.user_id == current_user.id %>
          <td style="user-select: auto;"><%= link_to "Edit", edit_book_path, class: "btn-sm btn-success" %></td>　<!-- 変更 -->
          <td style="user-select: auto;"><%= link_to "Destroy", @books, method: :delete, "data-confirm" => "本当に削しますか？", class: "btn-sm btn-danger" %></td>　<!-- 変更 -->
          <% end %>
        </tr>
      </tbody>
    </table>

  </div>


</div>

app/views/homes/about.html.erb
<!-- 共通部分編集　<a>タグ編集　 -->


  	<div class="body">
      <div class="container">

        <p id="notice"></p>


      	<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>


      </div>
    </div>

app/views/homes/home.html.erb
<!-- 共通部分編集　<a>タグ編集　 -->

<header class="navbar navbar-fixed-top navbar-inverse" style="user-select: auto;">
  <div class="container" style="user-select: auto;">
    <nav class="nav navbar-nav navbar-left" style="user-select: auto;">
      <span style="user-select: auto;">Bookers</span>
    </nav>
    <nav style="user-select: auto;">
      <ul class="nav navbar-nav navbar-right" style="user-select: auto;">
          <li style="user-select: auto;"><a class="glyphicon glyphicon-home home" href="/" style="user-select: auto;"> Home</a></li>
          <li style="user-select: auto;"><a class="glyphicon glyphicon-link about" href="/home/about" style="user-select: auto;"> About</a></li>
          <li style="user-select: auto;"><a class="glyphicon glyphicon-edit sign_up" href="/users/sign_up" style="user-select: auto;"> sign up</a></li>
          <li style="user-select: auto;"><a class="glyphicon glyphicon-log-in sign_in" href="/users/sign_in" style="user-select: auto;"> login</a></li>
      </ul>
    </nav>
  </div>
</header>

  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <div class="body" style="user-select: auto;">
      <div class="container" style="user-select: auto;">

        <p id="notice" style="user-select: auto;">Signed out successfully.</p>


         <div class="row" style="user-select: auto;">
          <div class="top-message col-md-offset-3 col-md-6" style="user-select: auto;">
            <h1 style="user-select: auto;">welcome to <span class="glyphicon glyphicon-book" style="user-select: auto;"><strong style="user-select: auto;">Bookers</strong>  !!</span></h1>
              <p style="user-select: auto;">In  <span class="glyphicon glyphicon-book" style="user-select: auto;"></span><strong style="user-select: auto;">Bookers</strong>, </p>
              <p style="user-select: auto;">you can share and exchange  your opinions , inpressions , and emotions</p>
              <p style="user-select: auto;"> about various books!</p>

            <div class="btn-wrapper" style="user-select: auto;">
              <div class="row" style="user-select: auto;">
                 <p style="user-select: auto;"><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in" style="user-select: auto;">Log in</a></p>
              </div>
              <div class="row" style="user-select: auto;">
                <p style="user-select: auto;"><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up" style="user-select: auto;">Sign Up</a></p>
              </div>
            </div>

          </div>
        </div>


      </div>
    </div>

  <% end %>


    <footer style="user-select: auto;">
  <div class="container" style="user-select: auto;">
    <div class="row" style="user-select: auto;">
      <div class="col-xs-3 col-xs-offset-9" style="user-select: auto;">
        <p style="user-select: auto;">CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
<!-- 共通部分編集　<a>タグ編集　 -->




    <div class="body" style="user-select: auto;">
      <div class="container" style="user-select: auto;">

        <%= render 'template/flash.message' %>


         <div class="row" style="user-select: auto;">
          <div class="top-message col-md-offset-3 col-md-6" style="user-select: auto;">
            <h1 style="user-select: auto;">welcome to <span class="glyphicon glyphicon-book" style="user-select: auto;"><strong style="user-select: auto;">Bookers</strong>  !!</span></h1>
              <p style="user-select: auto;">In  <span class="glyphicon glyphicon-book" style="user-select: auto;"></span><strong style="user-select: auto;">Bookers</strong>, </p>
              <p style="user-select: auto;">you can share and exchange  your opinions , inpressions , and emotions</p>
              <p style="user-select: auto;"> about various books!</p>

            <div class="btn-wrapper" style="user-select: auto;">
              <div class="row" style="user-select: auto;">
                 <p style="user-select: auto;">
                  <%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in", style: "user-select: auto;" %>
                 </p>
              </div>
              <div class="row" style="user-select: auto;">
                <p style="user-select: auto;">
                  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up", style: "user-select: auto;" %>
                </p>
              </div>
            </div>

          </div>
        </div>


      </div>
    </div>

app/views/layouts/application.html.erb
<!-- signin後のリンク設定 -->

<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookers</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head>






  <body>

    <header class="navbar navbar-inverse" style="user-select: auto;">
      <div class="container">
        <nav class="nav navbar-nav navbar-left" style="user-select: auto;">
          <span style="user-select: auto;">Bookers</span>
        </nav>
        <nav style="user-select: auto;">
          <ul class="nav navbar-nav navbar-right" style="user-select: auto;">

          <% if user_signed_in? %>
            <li style="user-select: auto;"><%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %></li>
            <li style="user-select: auto;"><%= link_to " Users", users_path, class: "glyphicon glyphicon-user users" %></li>
            <li style="user-select: auto;"><%= link_to " Books", books_path, class: "glyphicon glyphicon-book books" %></li>
            <li style="user-select: auto;"><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>

          <% else %>
             <li style="user-select: auto;"><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
             <li style="user-select: auto;"><%= link_to " about", home_about_path, class: "glyphicon glyphicon-link about" %></li>
             <li style="user-select: auto;"><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
             <li style="user-select: auto;"><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>

          </ul>
        </nav>
      </div>
    </header>

    <div class="body" style="user-select: auto;">
      <div class="container" style="user-select: auto;">




    <%= yield %>

      </div>
    </div>

    <footer style="user-select: auto;">
      <div class="container" style="user-select: auto;">
        <div class="row" style="user-select: auto;">
          <div class="col-xs-3 col-xs-offset-9" style="user-select: auto;">
            <p style="user-select: auto;">CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/template/_error.message.html.erb
<% if @book.errors.any? %>
    <div id="error_explanation">
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved</h3>
        <ul>
            <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/template/_flash.message.html.erb
<% if flash[:notice] %>
    <p class="notice"><%= notice %></p>
<% end %>

app/views/template/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="user-select: auto;">
      <div class="container">
        <nav class="nav navbar-nav navbar-left" style="user-select: auto;">
          <span style="user-select: auto;">Bookers</span>
        </nav>
        <nav style="user-select: auto;">
          <ul class="nav navbar-nav navbar-right" style="user-select: auto;">

          <% if user_signed_in? %>
            <li style="user-select: auto;"><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
            <li style="user-select: auto;"><%= link_to " Users", home_about_path, class: "glyphicon glyphicon-user users" %></li>
            <li style="user-select: auto;"><%= link_to " Books", new_user_session_path, class: "glyphicon glyphicon-book books" %></li>
            <li style="user-select: auto;"><%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %></li>

          <% else %>
             <li style="user-select: auto;"><%= link_to " Home", root_path, class: "glyphicon glyphicon-home home" %></li>
             <li style="user-select: auto;"><%= link_to " about", home_about_path, class: "glyphicon glyphicon-link about" %></li>
             <li style="user-select: auto;"><%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %></li>
             <li style="user-select: auto;"><%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
          <% end %>



          </ul>
        </nav>
      </div>
    </header>

app/views/template/_sidebar.html.erb
<div class="col-xs-3" style="user-select: auto;">
  <h2 style="user-select: auto;">User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %> <!-- 変更 -->

  <table class="table" style="user-select: auto;">

    <tbody style="user-select: auto;"><tr style="user-select: auto;"></tr>
      <tr style="user-select: auto;">
        <th style="user-select: auto;">name</th>
        <th style="user-select: auto;"><%= @user.name %></th> <!-- 変更 -->
      </tr>
      <tr style="user-select: auto;">
        <th style="user-select: auto;">introduction</th>
        <th style="user-select: auto;"><%= @user.introduction %></th> <!-- 変更 -->
      </tr>
    </tbody>

  </table>

  <div class="row" style="user-select: auto;">
    <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %> <!-- 変更 -->
  </div>

  <h2 style="user-select: auto;">New book</h2>
  <%= form_for(@book) do |f| %> <!-- 変更 -->

    <div class="field row" style="user-select: auto;">
      <label for="book_title" style="user-select: auto;">Title</label>
      <%= f.text_field :title, class:"col-xs-12" %> <!-- 変更 -->
    </div>

    <div class="field row" style="user-select: auto;">
      <label for="book_opinion" style="user-select: auto;">Opinion</label>
      <%= f.text_area :body, class:"col-xs-12 book_body" %> <!-- 変更 -->
    </div>

    <div class="actions row" style="user-select: auto;">
      <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %> <!-- 変更 -->
    </div>

  　　<% end %> <!-- 変更 -->
</div>

app/views/users/edit.html.erb
<div class="body" style="user-select: auto;">
  <div class="container" style="user-select: auto;">

<!-- サクセスメッセージ -->
<%= render 'template/flash.message' %>

<h2 style="user-select: auto;">User info</h2>

<!-- エラーメッセージ -->
<% if @user.errors.any? %>
    <div id="error_explanation">
        <h3><%= @user.errors.count %>errors prohibited this obj from being saved</h3>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<!-- 投稿フォーム -->
<%= form_for(@user) do |f| %>


    <div class="field" style="user-select: auto;">
      <label for="user_name" style="user-select: auto;">Name</label>
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field" style="user-select: auto;">
      <label for="user_image" style="user-select: auto;">Image</label>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </div>

    <div class="field" style="user-select: auto;">
      <label for="user_introduction" style="user-select: auto;">Introduction</label>
      <%= f.text_area :introduction, class:"form-control", rows:"3", placeholder:"コメントここに" %>
    </div>

    <div class="actions" style="user-select: auto;">
      <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
    </div>

<% end %>
  </div>
</div>

<!--  -->

app/views/users/edit.thml.erb
<div class="body" style="user-select: auto;">
  <div class="container" style="user-select: auto;">

<!-- サクセスメッセージ -->
  <p id="notice" style="user-select: auto;"></p>



  <h2 style="user-select: auto;">User info</h2>

<%= form_for(@user) do |f| %>


    <div class="field" style="user-select: auto;">
      <label for="user_name" style="user-select: auto;">Name</label>
      <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="field" style="user-select: auto;">
      <label for="user_image" style="user-select: auto;">Image</label>
      <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
    </div>

    <div class="field" style="user-select: auto;">
      <label for="user_introduction" style="user-select: auto;">Introduction</label>
      <%= f.text_area :introduction, class:"form-control", rows:"3", placeholder:"コメントここに" %>
    </div>

    <div class="actions" style="user-select: auto;">
      <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
    </div>

<% end %>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'template/flash.message' %>


<div class="row" style="user-select: auto;">

<!-- 左側 -->


<%= render 'template/sidebar' %>

<!-- 右側 -->

  <div class="col-xs-9" style="user-select: auto;">
    <h2 style="user-select: auto;">Users</h2>

    <table class="table" style="user-select: auto;">
  <thead style="user-select: auto;">
    <tr style="user-select: auto;">
      <th style="user-select: auto;">image</th>
      <th style="user-select: auto;">name</th>
      <th colspan="3" style="user-select: auto;"></th>
    </tr>
  </thead>

  <tbody style="user-select: auto;">
    <% @users.each do |user| %>


      <tr style="user-select: auto;">
        <td style="user-select: auto;"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td style="user-select: auto;"><%= user.name %></td>
        <td style="user-select: auto;"><%= link_to " Show", user_path(user.id) %></td>
      </tr>

    <% end %>
  </tbody>
</table>

  </div>

</div>

app/views/users/show.html.erb
<!-- サクセスメッセージ -->
<%= render 'template/flash.message' %>

<div class="row" style="user-select: auto;">
<!-- 左側 -->

<%= render 'template/sidebar' %>


<!-- 右側 -->


  <div class="col-xs-9" style="user-select: auto;">
    <h2 style="user-select: auto;">Books</h2>

    <table class="table table-hover table-inverse" style="user-select: auto;">
  <thead style="user-select: auto;">
    <tr style="user-select: auto;">
      <th style="user-select: auto;"></th>
      <th style="user-select: auto;">Title</th>
      <th style="user-select: auto;">Opinion</th>
      <th colspan="3" style="user-select: auto;"></th>
    </tr>
  </thead>

  <tbody style="user-select: auto;">
    <% @books.each do |book| %> <!-- 変更 -->

      <tr style="user-select: auto;">
        <td style="user-select: auto;">
          <%= link_to user_path(book.user_id) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
          <% end %>　<!-- 変更 -->
        </td>
        <td style="user-select: auto;"><%= link_to "#{book.title}", book_path(book.id) %></td>　<!-- 変更 -->
        <td style="user-select: auto;"><%= book.body %></td>　<!-- 変更 -->

    <% end %>　<!-- 変更 -->

  </tbody>
</table>
  </div>
</div>
      </div>
    </div>
</div>